server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wisdom-cloud-education?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #数据库连接超时时间
      connection-timeout: 30000
      #连接池最大连接数，默认是10
      maximum-pool-size: 30
      #最小空闲连接数量
      minimum-idle: 10
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期
      max-lifetime: 6000
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: 30
        max-idle: 8
        min-idle: 0
    host: 127.0.0.1
    password: 123456
pagehelper:
  helper-dialect: mysql #数据库方言，默认为mysql
  reasonable: true   #是否开启分页合理化
  support-methods-arguments: true #支持通过 Mapper 接口参数来传递分页参数
  params: count=countSql
file:
  upload: F:\\static\\ # 配置文件上传的根目录
ueditor:
  configFileName: config-dev.json
lbs:
  key: MYOBZ-OOEW3-KYC3G-YWDXA-DMQJ6-SPBMH
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
